<div class="col-sm-2 sidebar">
	<ul class="nav nav-sidebar">
		<li<?php echo $this->activeNav('admin')?>><a href="<?php echo SITE_BASE_URL.'admin/'?>">管理首页</a></li>
        <li<?php echo $this->activeNav('admin','docs')?>><a href="<?php echo SITE_BASE_URL.'admin/docs/'?>">医师信息维护</a></li>
        <li<?php echo $this->activeNav('admin','docs','adddoc')?>><a href="<?php echo SITE_BASE_URL.'admin/docs/adddoc'?>">添加医师信息</a></li>
	</ul>
</div>