<!DOCTYPE html>
<html lang="zh">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="this is description">
    <title>this is page title</title>
    <!-- Bootstrap core CSS -->
    <link href="<?php echo SITE_BASE_URL?>css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo SITE_BASE_URL?>css/global.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="<?php echo SITE_BASE_URL?>css/bootstrap-theme.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">铭壹堂</a>
        </div>
      </div>
    </div>

    <div class="container">
    <div class="row">
    	<div class="col-sm-3 sidebar">
    		<ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview</a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
    	</div>
    	<div class="col-sm-9 col-sm-offset-3 main"><?php echo $this->layout()->content; ?></div>
    </div>



    





    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/jquery-1.10.2.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>




