<style type="text/css">
.table td a{margin: 0 10px; display: block);
</style>
<h3 class="page-header">医师信息维护</h3>
<?php if(count($this->docList)>0){?>
<table class="table table-striped">
<tr><th>医师姓名</th><th>出诊时间</th><th>操作</th></tr>
<?php foreach($this->docList as $docInfo){?>
<tr><td><?php echo $docInfo->name?></td><td>--</td>
	<td><a href="<?php echo SITE_BASE_URL.'admin/docs/update?id='.$docInfo->id?>" class="btn btn-primary btn-sm">编辑</a>
		<a href="<?php echo SITE_BASE_URL.'admin/docs/delete?id='.$docInfo->id?>" class="btn btn-primary btn-sm">删除</a></td>
</tr>
<?php }?>
</table>
<?php }?>
<hr/>
<p><a href="<?php echo SITE_BASE_URL,'admin/docs/adddoc/'?>">添加医师信息</a></p>