<style type="text/css">
table td a{float: right;}
</style>
<h3 class="page-header">药材列表</h3>
<?php if(count($this->medsList)>0){?>
<table class="table table-striped table-bordered">
<tr><th width="10%">序号</th><th width="20%">药材名称</th><th width="10%">单位</th><th width="10%">库存数量</th><th width="10%">序号</th><th width="20%">药材名称</th><th width="10%">单位</th><th width="10%">库存数量</th></tr>
<?php
$num=1;
foreach($this->medsList as $med){
    if($num%2==1){
        echo "<tr><td>".$num."</td><td>".$med['med_name']."<a href=\"".SITE_BASE_URL."medicine/update?id=".$med['id']."\">编辑</a></td>
        <td>".$med['med_unit']."</td><td>".$this->calStock($med['id'])."</td>";
    }
    if($num%2==0){
        echo "<td>".$num."</td><td>".$med['med_name']."<a href=\"".SITE_BASE_URL."medicine/update?id=".$med['id']."\">编辑</a></td>
        <td>".$med['med_unit']."</td><td>".$this->calStock($med['id'])."</td></tr>";
    }
    $num++;
}
if($num%2==0){
    echo "<td>&nbsp;</td><td>&nbsp;</td></tr>";
}
?>
</table>




<?php }?>
